### PR TITLE
0.06wip3

### PR DESCRIPTION
**Pull request by jroatch**
0.06wip3 (2018-09-17)
* Sound engine updated to latest version of Pently.
  Consequently the old sound data was not converted.
* The correct number of CHR pages loads for CNROM titles.
* Moving left/right between pages doesn't force cursor to the ends
  of the page.
* RAM and Nametables are cleared when loading an activity.
* Descriptions compressed with DTE
* Graphics and activity CHR banks now compressed with "Donut"
* Added additional Characters to the VWF font.
  Control Pad  (suggested by M_Tee)
    https://forums.nesdev.com/viewtopic.php?p=215648#p215648
  and bird/Twitter logo from pinobatch/240p-test-mini
* Menu tabs overlap to give more space

### CODE REVIEW

**Comment by pinobatch** [comment]
This PR has a lot of changes for me to merge. It may take me a while to review everything.

**Comment by jroatch** [comment]
No problem, I just wanted to submit these changes before I started a long week of work without access to my computer.

The update to Pently is the one commit that needs a good long review. I might have botched something when copying files over.

**Comment by pinobatch** [comment]
When you imported newer version of Pently (and didn't turn off the space-intensive portamento feature because the chosen song uses it) in 050a1cd, you moved RODATA below $C000 to resolve an overflow of about 200 bytes, and you claimed that this measure is temporary. How will this be resolved?

**Comment by jroatch** [comment]
for the rewrite I'm planning on allocating different ranges for things. The title screen will be it's own 16KiB NROM ROM that may or may not be located in 8000-BFFF. C000-DFFF Will be for loading and menu code that will just have the sound effects part of Pently, and E000-FFFF is the area the builder will fill.

In the meantime, I guess I can disable pently features when some new titlescreen music will be composed (done by me if no one else is doing that). That alone may not be enough. So maybe I'll also clean up the older UI code for menu navigation or something.

**Comment by pinobatch** [comment]
So it'd boot to a title screen ROM that chain-loads the menu proper, and Pently would be duplicated in both. That could be useful depending on what demoscene-type stuff we can convince devs to make for the title screen. But for now, I can accept cutting the last bank's free space back to 14 KiB, so long as the builder is on board with it. I'll get to that.

**Pull request merged**
